POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "POST_TEST",
  "data": {
    "owner_id": 2,
    "description": "paint course",
    "questions": [
      {
        "solution": "2",
        "q_id": 1,
        "description": "what is 2!",
        "q_order": 1
      },
      {
        "solution": "A",
        "choices": [
          "java",
          "kotlin",
          "python"
        ],
        "q_id": 1,
        "description": "which is best",
        "q_order": 2
      }
    ]
  }
}

###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_COURSES",
  "data": {
    "owner_id": 2
  }
}

###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_QUESTIONS",
  "data": {
    "test_id": 1,
    "owner_id": 2
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_PREV_TESTS",
  "data": {
    "student_id": 28
  }
}

###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_RESULTS",
  "data": {
    "test_id": 2
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_ALL_RESULTS",
  "data": {
    "student_id": 28
  }
}

###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "POST_ANSWERS",
  "data":
   [
    {
      "t_id": 1,
      "q_id": 1,
      "description": "909",
      "owner_id": 1,
      "a_order": 1,
      "a_type": "MUTLI"
    },
    {
      "t_id": 1,
      "q_id": 1,
      "description": "long ansser",
      "owner_id": 1,
      "a_order": 2,
      "a_type": "LONG"
    }
  ]
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_ANSWERS",
  "data": {
    "test_id": 21,
    "owner_id": 28
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "POST_RESULT",
  "data": {
    "owner_id": 1,
    "t_id": 16,
    "score": 60,
    "owner_name": "test"
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "POST_MESSAGE",
  "data": {
    "student_id": 1,
    "teacher_id": 1,
    "message": "i did 'not get the idea"
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_MESSAGES",
  "data": {
    "teacher_id" : 10
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_PREV_TESTS",
  "data": {
    "student_id" : 28
  }
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "MARK_SEEN",
  "data": {
    "teacher_id": 1,
    "m_id": 3
  }
}
###
POST http://localhost/Anonymous_e_assessment/register.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "name": "student3",
  "sign": "hacker",
  "email": "student_4@gmail.com",
  "password": "student"
}
###
POST http://localhost/Anonymous_e_assessment/courses/course_service.php?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json

{
  "action": "GET_ALL_COURSES",
  "data": null
}
